apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: shopmicro
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: changeme-secure-password
