apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shopmicro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shopmicroregistry.azurecr.io/shopmicro-frontend:9364b22d6edbb6a1882d90c6922e18bf77760718
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
